[target.x86_64-unknown-none]
linker = "ld"
rustflags = [
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-zmax-page-size=0x1000",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "no-redzone=yes"
]


[alias]
run-os = "run --package xtask -- run"
build-os = "run --package xtask -- build"

